baseURL = "http://moberger.io/"
languageCode = "en-us"
title = "allimoblog"
theme = "custom" #based on 'minimal' but lots of modifications
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Allison Moberger"
    description = "Check this out."
    githubUsername = "allimo"
    showBorder = true
    font = "Sarabun" # should match the name on Google Fonts!
    
## syntax highlighting ##
# Uses highlightJS. See style gallery at https://highlightjs.org/static/demo/
    highlight = true
    highlightStyle = "solarized-dark" #all lowercase, hyphenated name from highlightJS
    highlightLanguages = ["r", "java", "bash", "json"]
    
## theme colors ##
    accent = "green"
    backgroundColor = "white"
    
## main site menu (left side) ##
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3
    

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

## social/icons menu (right side) ##
[[menu.icon]]
    url = "mailto:site@moberger.io"
    name = "envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/allimo/"
    name = "github"
    weight = 2
    
[[menu.icon]]
    url = "https://www.linkedin.com/in/allimo/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/allimoberger/"
    name = "twitter"
    weight = 4


